[package]
name = "aws-manager"
version = "0.0.18" # https://crates.io/crates/aws-manager/versions
edition = "2021"
rust-version = "1.63"
publish = true
description = "AWS SDK manager"
homepage = "https://github.com/gyuho/aws-manager"
license = "Apache-2.0"

[dependencies]
aws-config = "0.48.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-autoscaling = "0.19.0" # https://crates.io/crates/aws-sdk-autoscaling/versions
aws-sdk-cloudformation = "0.18.0" # https://crates.io/crates/aws-sdk-cloudformation/versions
aws-sdk-cloudwatch = "0.18.0" # https://crates.io/crates/aws-sdk-cloudwatch/versions
aws-sdk-cloudwatchlogs = "0.18.0" # https://crates.io/crates/aws-sdk-cloudwatchlogs/versions
aws-sdk-ec2 = "0.18.0" # https://crates.io/crates/aws-sdk-ec2/versions
aws-sdk-kms = "0.18.0" # https://crates.io/crates/aws-sdk-kms/versions
aws-sdk-s3 = "0.18.0" # https://crates.io/crates/aws-sdk-s3/versions
aws-sdk-sts = "0.18.0" # https://crates.io/crates/aws-sdk-sts/versions
aws-smithy-types = "0.48.0" # https://github.com/awslabs/smithy-rs/releases
aws-types = "0.48.0" # https://crates.io/crates/aws-types/versions
byteorder = "1.4.3"
chrono = "0.4.22" # https://github.com/chronotope/chrono/releases
command-manager = "0.0.1"
compress-manager = "0.0.2" # https://crates.io/crates/compress-manager/versions
http-manager = "0.0.2"
human-readable = "0.0.1"
hyper = { version = "0.14.20", features = ["full"] } # https://github.com/hyperium/hyper/releases
id-manager = "0.0.1"
log = "0.4.17"
random-manager = "0.0.1" # https://crates.io/crates/random-manager/versions
rfc-manager = "0.0.1"
ring = "0.16.20"
serde = { version = "1.0.144", features = ["derive"] } # https://github.com/serde-rs/serde/releases
serde_json = "1.0.85"
thiserror = "1.0.35"
tokio = { version = "1.21.1", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
tokio-stream = "0.1.10"

[dev-dependencies]
cmp-manager = "0.0.1"
env_logger = "0.9.1"
rust-embed = "6.4.1"
tempfile = "3.3.0"
tokio-test = "0.4.2"
