[package]
name = "aws-manager"
version = "0.0.12" # https://crates.io/crates/aws-manager/versions
edition = "2021"
rust-version = "1.62"
publish = true
description = "AWS manager"
homepage = "https://github.com/gyuho/aws-manager"
license = "Apache-2.0"

[dependencies]
aws-config = "0.46.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-cloudformation = "0.17.0"
aws-sdk-cloudwatch = "0.16.0"
aws-sdk-cloudwatchlogs = "0.16.0"
aws-sdk-ec2 = "0.16.0"
aws-sdk-kms = "0.16.0"
aws-sdk-s3 = "0.16.0"
aws-sdk-sts = "0.16.0"
aws-smithy-types = "0.46.0" # https://github.com/awslabs/smithy-rs/releases
aws-types = "0.46.0"
byteorder = "1.4.3"
chrono = "0.4.19"
command-manager = "0.0.1"
compress-manager = "0.0.2" # https://crates.io/crates/compress-manager/versions
http-manager = "0.0.1"
human-readable = "0.0.1"
hyper = { version = "0.14.20", features = ["full"] }
id-manager = "0.0.1"
log = "0.4.17"
random-manager = "0.0.1" # https://crates.io/crates/random-manager/versions
rfc-manager = "0.0.1"
ring = "0.16.20"
serde = { version = "1.0.141", features = ["derive"] } # https://github.com/serde-rs/serde/releases
serde_json = "1.0.82"
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
tokio-stream = "0.1.9"

[dev-dependencies]
cmp-manager = "0.0.1"
env_logger = "0.9.0"
rust-embed = "6.4.0"
tempfile = "3.3.0"
tokio-test = "0.4.2"
