[package]
name = "aws-manager"

# must be consistent with the "aws-sdk*" version
# e.g., "0.0.x" in "aws-manager" maps to "0.x.y" in "aws-sdk*" 
version = "0.19.8" # https://crates.io/crates/aws-manager/versions

edition = "2021"
rust-version = "1.64"
publish = true
description = "AWS SDK manager"
homepage = "https://github.com/gyuho/aws-manager"
license = "Apache-2.0"

[dependencies]
aws-config = "0.49.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-autoscaling = "0.19.0" # https://crates.io/crates/aws-sdk-autoscaling/versions
aws-sdk-cloudformation = "0.19.0" # https://crates.io/crates/aws-sdk-cloudformation/versions
aws-sdk-cloudwatch = "0.19.0" # https://crates.io/crates/aws-sdk-cloudwatch/versions
aws-sdk-cloudwatchlogs = "0.19.0" # https://crates.io/crates/aws-sdk-cloudwatchlogs/versions
aws-sdk-ec2 = "0.19.0" # https://crates.io/crates/aws-sdk-ec2/versions
aws-sdk-kms = "0.19.0" # https://crates.io/crates/aws-sdk-kms/versions
aws-sdk-s3 = "0.19.0" # https://crates.io/crates/aws-sdk-s3/versions
aws-sdk-ssm = "0.19.0" # https://crates.io/crates/aws-sdk-ssm/versions
aws-sdk-sts = "0.19.0" # https://crates.io/crates/aws-sdk-sts/versions
aws-smithy-types = "0.49.0" # https://github.com/awslabs/smithy-rs/releases
aws-types = "0.51.0" # https://crates.io/crates/aws-types/versions
byteorder = "1.4.3"
chrono = "0.4.22" # https://github.com/chronotope/chrono/releases
command-manager = "0.0.1"
compress-manager = "0.0.2" # https://crates.io/crates/compress-manager/versions
http-manager = "0.0.3"
human-readable = "0.0.1"
hyper = { version = "0.14.20", features = ["full"] } # https://github.com/hyperium/hyper/releases
id-manager = "0.0.1"
log = "0.4.17"
random-manager = "0.0.1" # https://crates.io/crates/random-manager/versions
rfc-manager = "0.0.1"
ring = "0.16.20"
serde = { version = "1.0.145", features = ["derive"] } # https://github.com/serde-rs/serde/releases
serde_json = "1.0.87"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
tokio-stream = "0.1.11"

[dev-dependencies]
cmp-manager = "0.0.1"
env_logger = "0.9.1"
rust-embed = "6.4.2"
tempfile = "3.3.0"
tokio-test = "0.4.2"
