# https://goreleaser.com/customization/builds/
builds:
  - id: aws-eni-provisioner
    binary: aws-eni-provisioner
    main: ./aws-eni-provisioner
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s -w
      - -X github.com/gyuho/infra/aws/go/cmd/version.GitCommit={{.Commit}}
      - -X github.com/gyuho/infra/aws/go/cmd/version.BuildTime={{.Date}}
      # - -X github.com/gyuho/infra/aws/go/cmd/version.ReleaseVersion={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: aws-instance-route-provisioner
    binary: aws-instance-route-provisioner
    main: ./aws-instance-route-provisioner
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s -w
      - -X github.com/gyuho/infra/aws/go/cmd/version.GitCommit={{.Commit}}
      - -X github.com/gyuho/infra/aws/go/cmd/version.BuildTime={{.Date}}
      # - -X github.com/gyuho/infra/aws/go/cmd/version.ReleaseVersion={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: aws-ip-provisioner
    binary: aws-ip-provisioner
    main: ./aws-ip-provisioner
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s -w
      - -X github.com/gyuho/infra/aws/go/cmd/version.GitCommit={{.Commit}}
      - -X github.com/gyuho/infra/aws/go/cmd/version.BuildTime={{.Date}}
      # - -X github.com/gyuho/infra/aws/go/cmd/version.ReleaseVersion={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: aws-volume-provisioner
    binary: aws-volume-provisioner
    main: ./aws-volume-provisioner
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s -w
      - -X github.com/gyuho/infra/aws/go/cmd/version.GitCommit={{.Commit}}
      - -X github.com/gyuho/infra/aws/go/cmd/version.BuildTime={{.Date}}
      # - -X github.com/gyuho/infra/aws/go/cmd/version.ReleaseVersion={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

# https://goreleaser.com/customization/archive/
archives:
  - id: aws-eni-provisioner
    format: tar.gz

    builds:
    - aws-eni-provisioner

    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

  - id: aws-instance-route-provisioner
    format: tar.gz

    builds:
    - aws-instance-route-provisioner

    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

  - id: aws-ip-provisioner
    format: tar.gz

    builds:
    - aws-ip-provisioner

    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

  - id: aws-volume-provisioner
    format: tar.gz
    builds:
    - aws-volume-provisioner

    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .Binary }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  replace_existing_draft: true
  make_latest: true
  mode: replace

  github:
    owner: gyuho
    name: infra

  header: |
    ## Some title ({{ .Date }})

    Welcome to this new release!

  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
