name: Release aws/go/cmd

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache: true

      # - name: Create "v0.0.0-latest" tag and run goreleaser
      #   run: |
      #     git push origin --delete v0.0.0-latest || true
      #     git tag --force v0.0.0-latest
      #     git push origin --tags
      #     go install github.com/goreleaser/goreleaser@latest
      #     goreleaser release --clean --snapshot
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release
          workdir: ./aws/go/cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release latest
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: Latest release
          tag_name: latest
          draft: false
          prerelease: false
          body: Latest builds from the last commit.
          files: |
            ./aws/go/cmd/dist/aws-eni-provisioner-linux-i386.tar.gz
            ./aws/go/cmd/dist/aws-eni-provisioner-linux-arm64.tar.gz
            ./aws/go/cmd/dist/aws-eni-provisioner-linux-x86_64.tar.gz
            ./aws/go/cmd/dist/aws-ip-provisioner-linux-i386.tar.gz
            ./aws/go/cmd/dist/aws-ip-provisioner-linux-arm64.tar.gz
            ./aws/go/cmd/dist/aws-ip-provisioner-linux-x86_64.tar.gz
            ./aws/go/cmd/dist/aws-volume-provisioner-linux-i386.tar.gz
            ./aws/go/cmd/dist/aws-volume-provisioner-linux-arm64.tar.gz
            ./aws/go/cmd/dist/aws-volume-provisioner-linux-x86_64.tar.gz
